### ISSUE TITLE
AKAuthenticationError Code=-7026 with LoginWithAppleId()

### ISSUE THREAD

**Issue by Aramir92** [lupidan/apple-signin-unity#55] opened 2020-07-30 10:14 UTC
When I try to make a LoginWithAppleId() I get the error: "Authorization failed: AKAuthenticationError Code=-7026 UserInfo={AKClientBundleID=<private>}". I've read it is invoked when you don't add the "Sign in with Apple" capability or if you don't enable it on the Apple developer page, but I did both. I've also tried to configure Xcode with capability and framework with a PostProcess method and manually and I've tried with different Ad Hoc and App Store (using TestFlight) provisioning profiles.
The strange thing is that the sign in works well in the Xcode Simulator and not in iOS 13 devices.

I'm using Unity 2018.4.17f1 with Firebase Authentication.

**Comment by lupidan** [comment] 2020-08-03 10:53
Could you please provide a small Unity project that reproduces this issue?

**Comment by Aramir92** [comment] 2020-08-05 09:45
Yes, sure. Here you can find a zip with a test project https://drive.google.com/file/d/15fjc-osZxMcwI2bAxCOK4u_B6xB8WCtb/view?usp=sharing
I've tested it with my provisioning profiles obtaining the same result: it works and returns me a token in the Xcode Simulator and it gives me the same error in iOS 13 devices.
Let me know if you need anything else.

**Comment by lupidan** [comment] 2020-08-07 09:21
- I compiled your project, as it is, into an Xcode Project with Unity 2018.3.14f1.
- Once the Xcode project was built, I just changed the Bundle Id of the project to match one I have, and works for me.
- I ran the app in an iOS 13 device

![IMG_0028](https://user-images.githubusercontent.com/1314521/89630457-b2d62600-d89f-11ea-95fd-bf8c3ada5a80.PNG)

**It works for me.** The issue must be your Apple codesigning/certificate setup, and therefore, it's outside the scope of this repository.

Please check the official Getting started section for Sign In With Apple:
[https://developer.apple.com/sign-in-with-apple/get-started/](https://developer.apple.com/sign-in-with-apple/get-started/)

Closing this

**Closed by lupidan** 2020-08-07 09:21 UTC

**Comment by Aramir92** [comment] 2020-08-07 17:35
Ok, I will check my certificates again. Thank you so much.
