### ISSUE TITLE
QuickLogin: AuthorizationCode is null

### ISSUE THREAD

**Issue by derwaldgeist** [lupidan/apple-signin-unity#133] opened 2021-11-13 15:14 UTC
As a follow-up to https://github.com/lupidan/apple-signin-unity/issues/132, which could be resolved by using version 1.4.2, I am still facing a problem with the QuickLogin under iOS 15.1:

My code now throws an NRE because `appleIdCredential.AuthorizationCode` is `null` (previously, it was always set). Note that `IdentityToken` _is_ available (not `null`). Just the `AuthorizationCode` is `null`.

I also noticed that - if that happens - `AuthorizationCode` is still null when I then try to login with the regular login, i.e. without using QuickLogin. *Only* if I restart the app completely, skip the QuickLogin and *then* use the regular Apple login, the `AuthorizationCode` returns a value again.

So it seems as if QuickLogin won't deliver an authorization code anymore, which basically breaks the functionality, as I need both tokens to login to my app.  :-/

**Comment by lupidan** [comment] 2021-11-13 16:52
From my experience, it seems **now** Apple only gives the Authorization Code + Identity Token the **FIRST** time a user SIWA on your app. Following quick logins, Apple just sends the Identity Token. (unless you previously revoke credentials from the settings)

I can find a similar question here:
* https://developer.apple.com/forums/thread/675578

There were some discussions here as well, and I gathered some thoughts which _may or may not be correct_.
* https://github.com/lupidan/apple-signin-unity/issues/118

In any case, the plugin just works as a wrapper around the native Apple's response. It could be that `ASAuthorizationController` is broken when requesting existing credentials the way Apple intended us to do it, which wouldn´t surprise me at all... There have been issues with QuickLogin and iPadOS 15 in the past too.
* https://github.com/lupidan/apple-signin-unity/issues/119#issuecomment-937001740

Do you get a null authorization code, with a user that already gave SIWA permissions, if you use `LoginWithAppleId` instead of `QuickLogin`? If that´s the case, it sounds like an iOS 15 bug to me

**Comment by derwaldgeist** [comment] 2021-11-13 17:14
Hi, thanks for the fast response. If I `LoginWithAppleId` right after app start, I get the authorization code.

However, if I do this right after calling `QuickLogin` (which fails because of the missing authorization code), then `LoginWithAppleId` won't return an authorization code either. This is different from before (pre iOS 15?), where I got the authorization code in all cases.

BTW: I was able to change my server code. Turned out that the authorization code was not actually needed to perform a re-login (on quick login). Feel free to close this issue, although the root cause still persists.

**Comment by lupidan** [comment] 2021-11-13 17:34
Yeah, my [initial conclusions](https://github.com/lupidan/apple-signin-unity/issues/118#issuecomment-926906778) about this, is that apple just wants you to use that Authorization Code once, to get a refresh token every day, and check if the user is still valid or they have somehow revoked credentials. So it could make sense you only get it once the first time a user signs in ¿?

I'm glad to hear you sorted it out in your backend. Unfortunately there is not much we can do besides ask in the official Apple forum if this is a bug, or the expected behaviour 🤷 

Closing this

**Closed by lupidan** 2021-11-13 17:34 UTC

**Comment by lupidan** [comment] 2022-02-16 20:40
Yeah, I guess one side effect from the authorization code being null after the first time is that the example is no longer valid and should probably be updated.

However the identity token should never be null AFAIK, so only a null check on the authorization code should be required.
The documentation needs to be updated yes 👍
